// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectOrangeApi.Data;

#nullable disable

namespace ProjectOrangeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526045713_AddCategoryNameToCartItem")]
    partial class AddCategoryNameToCartItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectOrangeApi.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.CartItemAddon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CartItemId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartItemId");

                    b.ToTable("CartItemAddons");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.CartVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("CartVouchers");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple smartphone",
                            ImageUrl = "",
                            Name = "iPhone 15",
                            Price = 59999m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Android flagship smartphone",
                            ImageUrl = "",
                            Name = "Samsung Galaxy S24",
                            Price = 54999m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Google AI smartphone",
                            ImageUrl = "",
                            Name = "Google Pixel 8",
                            Price = 39999m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "High-performance Android phone",
                            ImageUrl = "",
                            Name = "Xiaomi 14",
                            Price = 32999m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Fast charging flagship phone",
                            ImageUrl = "",
                            Name = "OnePlus 12",
                            Price = 45999m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Lightweight Apple laptop",
                            ImageUrl = "",
                            Name = "MacBook Air M3",
                            Price = 69999m,
                            StockQuantity = 7
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Premium Windows ultrabook",
                            ImageUrl = "",
                            Name = "Dell XPS 13",
                            Price = 74999m,
                            StockQuantity = 6
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Business laptop",
                            ImageUrl = "",
                            Name = "Lenovo ThinkPad X1 Carbon",
                            Price = 89999m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Gaming laptop",
                            ImageUrl = "",
                            Name = "ASUS ROG Zephyrus G14",
                            Price = 94999m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Portable productivity laptop",
                            ImageUrl = "",
                            Name = "Acer Swift Go 14",
                            Price = 39999m,
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "RGB keyboard",
                            ImageUrl = "",
                            Name = "Mechanical Keyboard",
                            Price = 3500m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Ergonomic wireless mouse",
                            ImageUrl = "",
                            Name = "Wireless Mouse",
                            Price = 1200m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Multi-port USB-C adapter",
                            ImageUrl = "",
                            Name = "USB-C Hub",
                            Price = 1800m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Aluminum adjustable stand",
                            ImageUrl = "",
                            Name = "Laptop Stand",
                            Price = 1500m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Wireless over-ear headphones",
                            ImageUrl = "",
                            Name = "Noise Cancelling Headphones",
                            Price = 8999m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Portable speaker",
                            ImageUrl = "",
                            Name = "Bluetooth Speaker",
                            Price = 2500m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Full HD webcam",
                            ImageUrl = "",
                            Name = "Webcam 1080p",
                            Price = 2200m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Portable high-speed SSD",
                            ImageUrl = "",
                            Name = "External SSD 1TB",
                            Price = 6500m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Fast-charging power bank",
                            ImageUrl = "",
                            Name = "Power Bank 20000mAh",
                            Price = 2000m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "QHD productivity monitor",
                            ImageUrl = "",
                            Name = "27-inch Monitor",
                            Price = 12999m,
                            StockQuantity = 10
                        });
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.CartItem", b =>
                {
                    b.HasOne("ProjectOrangeApi.Models.Cart", "Cart")
                        .WithMany("Entries")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.CartItemAddon", b =>
                {
                    b.HasOne("ProjectOrangeApi.Models.CartItem", "CartItem")
                        .WithMany("Addons")
                        .HasForeignKey("CartItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartItem");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.CartVoucher", b =>
                {
                    b.HasOne("ProjectOrangeApi.Models.Cart", "Cart")
                        .WithMany("AppliedVouchers")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.OrderItem", b =>
                {
                    b.HasOne("ProjectOrangeApi.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("ProjectOrangeApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.Product", b =>
                {
                    b.HasOne("ProjectOrangeApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.Cart", b =>
                {
                    b.Navigation("AppliedVouchers");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.CartItem", b =>
                {
                    b.Navigation("Addons");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProjectOrangeApi.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
